<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="JCPSI1439" ignored="0" name="smoke" tests="1" failures="1" timestamp="20 Jan 2019 08:15:18 GMT" time="31.813" errors="0">
  <testcase name="SampleTest" time="31.129" classname="com.qmetry.qaf.automation.step.client.Scenario">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at .When login to fb with credential 'nagarjuna.reddy76@gmail.com' and 'Jcpnaga@123'(scenarios/fusion/suite1.bdd:6)
	at qaf.example.steps.StepsLibrary.login(StepsLibrary.java:62)
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:159)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:134)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:173)
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:225)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- SampleTest -->
</testsuite> <!-- smoke -->
